---
- name: Error Handling
  hosts: all
  tasks:
   - block:
      - name: Install git using apt module
        apt:
         name: git
         state: present
         update_cache: yes
     rescue:
      - name: Install git using the yum module
        yum:
         name: git
         state: present
         update_cache: yes
...
