---              
- name: Configuring tomcat9
  hosts: all
  tasks:
   - name: Install tomcat9
     apt:
      name: tomcat9
      state: present
   - name: Copy the tomcat-users.xml file
     copy:
      src: tomcat-users.xml
      dest: /etc/tomcat9
   - name: Change port of tomcat from 9090 to 8080
     replace: 
      regexp: 9090
      replace: 8080
      path: /etc/tomcat9/server.xml
   - name: Pause ansible playbook
     pause:
      minutes: 3
   - name: Check response of tomcat on server1
     uri:
      url: http://172.31.125.129:8080
      status_code: 200
   - name: Check response of tomcat on server2
     uri:
      url: http://172.31.95.89:8080
      status_code: 200
...
